name: public_key_pinning_android
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  public_key_pinning_platform_interface:
    git:
      url: https://github.com/Kunnatam/flutter_public_key_pinning.git
      path: public_key_pinning_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.klaa.public_key_pinning_android
        pluginClass: PublicKeyPinningAndroidPlugin


