name: public_key_pinning
description: Flutter plugin for SSL pinning using public key.
version: 0.0.1
repository: https://github.com/Kunnatam/flutter_public_key_pinning/tree/master/public_key_pinning
issue_tracker: https://github.com/Kunnatam/flutter_public_key_pinning/issues
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  public_key_pinning_platform_interface:
    git:
      url: https://github.com/Kunnatam/flutter_public_key_pinning.git
      path: public_key_pinning_platform_interface
  public_key_pinning_ios:
    git:
      url: https://github.com/Kunnatam/flutter_public_key_pinning.git
      path: public_key_pinning_ios
  public_key_pinning_android:
    git:
      url: https://github.com/Kunnatam/flutter_public_key_pinning.git
      path: public_key_pinning_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        default_package: public_key_pinning_android
      ios:
        default_package: public_key_pinning_ios