name: public_key_pinning
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  public_key_pinning_platform_interface:
    git:
      url: git://github.com/Kunnatam/flutter_public_key_pinning.git
      path: public_key_pinning_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: com.klaa.public_key_pinning.public_key_pinning
        pluginClass: PublicKeyPinningPlugin
      ios:
        pluginClass: PublicKeyPinningPlugin